### ISSUE TITLE
Magic: Breath has an ambiguous menace

### ISSUE THREAD

**Issue by Unclebaby** [raleel/mythras-srd#17]
_Breath permits the recipient to hold their breath for an extended period, so that they can temporarily venture into harmful environments, such as underwater; or atmospheres tainted by rock dust, gases, smoke, or poisons. The spell lasts for a maximum of half the caster's POW in minutes, during which time the recipient cannot speak, or the breath is lost, **and they immediately begin to asphyxiate (or become poisoned).**_

My reading says that bolded consequence happens because the spell recipient is in poison gas clouds or some such, however, it could be read to say that the Breath spell won't allow you to take another breath of wholesome air till the spell expires either. That would make it a fairly potent and torturous offensive spell.

I would want to edit that text to say something like "...and they must immediately begin to breathe from their environment suffering any associated risks such as asphyxiation (or becoming poisoned).

What say you? Do you agree it should have no menace implied? And, if so, do you want it left as is even so?

**Comment by raleel** [comment]
how about such as asphyxiation, drowning, or poisoning? make it a little clearer that it is whatever the environment is.

**Comment by Unclebaby** [comment]
_Breath permits the recipient to hold their breath for an extended period, so that they can temporarily venture into harmful environments, such as underwater; or atmospheres tainted by rock dust, gases, smoke, or poisons. The spell lasts for a maximum of half the caster's POW in minutes, during which time the recipient cannot speak, or the breath is lost, and they must immediately begin to breathe from their environment suffering any present risks - be that asphyxiation, drowning, poisoning, etc._

This works?

**Comment by Unclebaby** [comment]
Final edit for now.


### Breath

Touch

Breath permits the recipient to hold their breath for an extended period, so that they can temporarily venture into harmful environments, such as underwater; or atmospheres tainted by rock dust, gases, smoke, or poisons. The spell lasts for a maximum of half the caster's POW in minutes, during which time the recipient cannot speak, or the breath is lost, and they must immediately begin to breathe from their environment suffering any present risks - be that asphyxiation, drowning, poisoning, etc.

<details>

<summary>* Community Errata</summary>

#### _Breath_

_The original spell description was as follows: "Breath permits the recipient to hold their breath for an extended period, so that they can temporarily venture into harmful environments, such as underwater; or atmospheres tainted by rock dust, gases, smoke, or poisons. The spell lasts for a maximum of half the caster's POW in minutes, during which time the recipient cannot speak, or the breath is lost, and they immediately begin to asphyxiate (or become poisoned)."_

_This could be read as an offensive effect triggered at the spell's end, which seems counter to the authors' intention and the pattern of such spells as utilities rather than weapons. Hence the Community Errata edit above. We will update this text should the original authors revise the rule as written._

</details>
